version: 0.2

phase:
  install:
    runtime-version:
      nodejs:18
    commands:
      - echo installing dependencies
      - npm ci --legacy-peer-dependencies


  build:
    commands:
      - echo building the react app...
      - npm run buid  


  artifacts:
    files:
     -'**/*'
    base-directory : dist
    discard-path: no    